### ISSUE TITLE
EPUB vs. WebPub content type mismatch, intentional? (to test processing tools?)

### ISSUE THREAD

**Issue by danielweck** [opds-community/test-catalog#1]
https://github.com/opds-community/test-catalog/blob/389bd81e9fa17309d2de1d676577a153545ef4c6/2.0/home.json#L227-L228

https://github.com/opds-community/test-catalog/blob/389bd81e9fa17309d2de1d676577a153545ef4c6/2.0/home.json#L251-L252

https://github.com/opds-community/test-catalog/blob/389bd81e9fa17309d2de1d676577a153545ef4c6/2.0/home.json#L275-L276

https://github.com/opds-community/test-catalog/blob/389bd81e9fa17309d2de1d676577a153545ef4c6/2.0/home.json#L303-L304

**Comment by HadrienGardeur** [comment]
Initially this was on purpose, when the only feed available was the home. But now that I've moved most test to a separate feed, this should be removed from the home feed IMO.
